spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
        - id: validation-service
          uri: ${VALIDATION_SERVICE_URL:http://validation-service:8082}
        - id: project-service
          uri: ${PROJECT_SERVICE_URL:http://project-service:8083}
        - id: finance-service
          uri: ${FINANCE_SERVICE_URL:http://finance-service:8084}
        - id: prototype-service
          uri: ${PROTOTYPE_SERVICE_URL:http://prototype-service:8085}
        - id: metrics-service
          uri: ${METRICS_SERVICE_URL:http://metrics-service:8086}

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}
